version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount only the necessary development files
      - ./app.py:/app/app.py
      - ./scribe_core.py:/app/scribe_core.py
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
